//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using Newtonsoft.Json;
using winsdkfb;

using Windows.ApplicationModel.Core;
using Windows.UI.Xaml.Data;

namespace LoginCs
{
    public class MyFBPage : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        protected virtual void OnPropertyChanged(
            string propName
            )
        {
            PropertyChangedEventHandler h = PropertyChanged;
            if (h != null)
            {
                h(this, new PropertyChangedEventArgs(propName));
            }
        }
     
        public MyFBPage()
        {
            _id = null;
            _category = null;
            _description = null;
            _link = null;
            _name = null;
        }
        public string Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
                OnPropertyChanged("Id");
            }
        }
        public string Category
        {
            get
            {
                return _category;
            }
            set
            {
                _category = value;
                OnPropertyChanged("Category");
            }
        }
        public int Checkins
        {
            get
            {
                return _checkins;
            }
            set
            {
                _checkins = value;
                OnPropertyChanged("Checkins");
            }
        }
        public string Description
        {
            get
            {
                return _description;
            }
            set
            {
                _description = value;
                OnPropertyChanged("Description");
            }
        }
        public int Likes
        {
            get
            {
                return _likes;
            }
            set
            {
                _likes = value;
                OnPropertyChanged("Likes");
            }
        }
        public string Link
        {
            get
            {
                return _link;
            }
            set
            {
                _link = value;
                OnPropertyChanged("Link");
            }
        }
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
                OnPropertyChanged("Name");
            }
        }
        public static MyFBPage FromJson(
            string JsonText
            )
        {
            MyFBPage obj = 
                JsonConvert.DeserializeObject<MyFBPage>(JsonText);
            return obj;
        }
        private string _id;
        private string _category;
        private int _checkins;
        private string _description;
        private int _likes;
        private string _link;
        private string _name;
    }
}



